### ISSUE TITLE
Default installation

### ISSUE THREAD

**Issue by chuwilliamson** [slanden/Sappi#11]
Make a self extracter for windows that places the correct files in the proper directories.

**Comment by slanden** [comment]
part of #18 Application Deployment

**Comment by chuwilliamson** [comment]
do you have a working app yet? need to reschedule with ross

**Comment by slanden** [comment]
It works, I haven't managed to make an installer for it yet, but right now
all you need to do is unzip it in a Program Files folder or anywhere and
it'll work.

**Comment by slanden** [comment]
I don't have Ross' email, but I'm ready to schedule an appointment with him
and yourself if you want to sit in or give feedback. I got passed the
install issues as well as some other xp grinding along the way and a
working link is provided on github.
